name: sentiment_dart
description: Sentiment Dart is a dart module that uses the AFINN-165 wordlist to perform sentiment analysis on arbitrary blocks of text
version: 0.0.3
homepage: https://github.com/buckthorndev/sentiment_dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  remove_emoji: ^0.0.2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
